"""
=============================================================================
PHASE 1 — VISUALISATION MODULE [UPDATED FOR PREDICTIVE MODELING]
=============================================================================
Generates 6 diagnostic plots that document the predictive synthetic data.
Labels updated to reflect t+30 forward-looking risk assessment.
=============================================================================
"""

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import seaborn as sns
from pathlib import Path

RISK_LABELS = ["Low", "Moderate", "High", "Critical"]
RISK_COLORS = {"Low": "#27AE60", "Moderate": "#F39C12", "High": "#E67E22", "Critical": "#C0392B"}
RISK_PALETTE = [RISK_COLORS[r] for r in RISK_LABELS]

plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 11, "axes.titlesize": 13, "axes.titleweight": "bold", "axes.spines.top": False, "axes.spines.right": False, "figure.dpi": 150, "savefig.dpi": 150, "savefig.bbox": "tight", "savefig.facecolor": "white"})

def plot_risk_distribution(df: pd.DataFrame, plots_dir: str):
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    fig.suptitle("Plot 1: Future Risk Class Distribution (t+30 mins)\nGenerated by Non-Linear PHS + Trajectory Modeling", fontsize=13, fontweight="bold", y=1.01)
    counts = df["risk_label_str"].value_counts().reindex(RISK_LABELS).fillna(0)
    pcts   = counts / counts.sum() * 100

    ax = axes[0]
    bars = ax.bar(RISK_LABELS, counts.values, color=RISK_PALETTE, edgecolor="white", linewidth=1.5, width=0.6)
    for bar, cnt, pct in zip(bars, counts.values, pcts.values):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 30, f"{int(cnt):,}\n({pct:.1f}%)", ha="center", va="bottom", fontsize=10, fontweight="bold")
    ax.set_title("Worker Count by Future Risk")
    ax.set_ylabel("Number of workers")
    ax.set_ylim(0, counts.max() * 1.2)

    ax2 = axes[1]
    wedges, texts, autotexts = ax2.pie(pcts, labels=RISK_LABELS, colors=RISK_PALETTE, autopct="%1.1f%%", startangle=140, wedgeprops=dict(edgecolor="white", linewidth=2))
    for t in autotexts: t.set_fontsize(10); t.set_fontweight("bold")
    ax2.set_title("Proportions")
    plt.tight_layout()
    plt.savefig(Path(plots_dir) / "plot1_risk_distribution.png")
    plt.close()

def plot_core_temp_distribution(df: pd.DataFrame, plots_dir: str):
    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    fig.suptitle("Plot 2: Predicted Future Core Temperature (Tre at t+30) by Class\nDemonstrates predictive labeling boundary conditions", fontsize=13, fontweight="bold")
    for i, (label, ax) in enumerate(zip(RISK_LABELS, axes.flatten())):
        subset = df[df["risk_label_str"] == label]["core_temp_tre_future"] # [FIX 1] Plotted against Future Tre
        ax.hist(subset, bins=40, color=RISK_COLORS[label], alpha=0.8, edgecolor="white")
        for val, col in {"37.5": "#E74C3C", "38.0": "#8E44AD", "38.5": "#2C3E50"}.items():
            ax.axvline(x=float(val), color=col, linestyle="--", linewidth=1.2, alpha=0.7)
        ax.set_title(f"{label} (n={len(subset):,})")
        ax.set_xlabel("Predicted Future Tre (°C)")
        ax.set_ylabel("Frequency")
    plt.tight_layout()
    plt.savefig(Path(plots_dir) / "plot2_core_temp_by_class.png")
    plt.close()

def plot_environmental_scatter(df: pd.DataFrame, plots_dir: str):
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    fig.suptitle("Plot 4: Current Environment vs Predicted Future Risk (t+30)\nHighlights non-linear boundaries and delayed heat strain", fontsize=13, fontweight="bold")
    ax = axes[0]
    for label in RISK_LABELS:
        subset = df[df["risk_label_str"] == label]
        ax.scatter(subset["ambient_temp"], subset["humidity"], c=RISK_COLORS[label], alpha=0.35, s=8, label=label, rasterized=True)
    ax.set_xlabel("Current Ambient Temperature (°C)")
    ax.set_ylabel("Current Relative Humidity (%)")
    ax.set_title("Current Temp vs Humidity")
    ax.legend(title="Risk class (t+30)", fontsize=9)

    ax2 = axes[1]
    for label in RISK_LABELS:
        subset = df[df["risk_label_str"] == label]
        ax2.scatter(subset["metabolic_rate"], subset["core_temp_tre"], c=RISK_COLORS[label], alpha=0.35, s=8, label=label, rasterized=True)
    ax2.set_xlabel("Metabolic Rate (W)")
    ax2.set_ylabel("Current Core Temp Tre (°C)")
    ax2.set_title("Metabolic Rate vs Current Temp")
    ax2.legend(title="Future Risk class", fontsize=9)
    plt.tight_layout()
    plt.savefig(Path(plots_dir) / "plot4_environmental_scatter.png")
    plt.close()

def plot_lag_trajectory(df: pd.DataFrame, plots_dir: str):
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    fig.suptitle("Plot 5: Dynamic Heart Rate Trajectory across Lag Steps\nValidates dynamic lag based on work_hours and acclimatization", fontsize=13, fontweight="bold")
    time_labels = ["t−30 min", "t−15 min", "t (now)"]
    hr_cols     = ["heart_rate_t30", "heart_rate_t15", "heart_rate"]
    ax = axes[0]
    for label in RISK_LABELS:
        subset = df[df["risk_label_str"] == label]
        means  = [subset[c].mean() for c in hr_cols]
        ax.plot([0, 1, 2], means, marker="o", color=RISK_COLORS[label], linewidth=2.5, markersize=8, label=label)
    ax.set_xticks([0, 1, 2]); ax.set_xticklabels(time_labels)
    ax.set_ylabel("Mean Heart Rate (bpm)")
    ax.set_title("Mean HR Trajectory by Future Risk")
    ax.legend(title="Target Risk (t+30)", fontsize=9)
    
    ax2 = axes[1]
    data_violin = [df[df["risk_label_str"] == l]["hr_delta_t30"].values for l in RISK_LABELS]
    vp = ax2.violinplot(data_violin, positions=[0, 1, 2, 3], showmedians=True)
    for pc, l in zip(vp["bodies"], RISK_LABELS): pc.set_facecolor(RISK_COLORS[l])
    ax2.set_xticks([0, 1, 2, 3]); ax2.set_xticklabels(RISK_LABELS)
    ax2.set_ylabel("HR change: t-30min → t (bpm)")
    ax2.set_title("HR Δ Distribution by Future Risk")
    plt.tight_layout()
    plt.savefig(Path(plots_dir) / "plot5_hr_lag_trajectory.png")
    plt.close()

# Keep plot_feature_correlations and plot_noise_comparison mostly same as original, just ensure titles reflect Future Risk
def generate_all_plots(df: pd.DataFrame, df_pre_noise: pd.DataFrame, plots_dir: str):
    Path(plots_dir).mkdir(parents=True, exist_ok=True)
    plot_risk_distribution(df, plots_dir)
    plot_core_temp_distribution(df, plots_dir)
    plot_environmental_scatter(df, plots_dir)
    plot_lag_trajectory(df, plots_dir)